export const openapiDocument = {
  openapi: "3.0.3",
  info: { title: "SmartEV Vision API", version: "0.1.0", description: "Phase 0 — auth & users" },
  servers: [{ url: "/api/v1" }],
  paths: {
    "/auth/register": { post: { summary: "Register", responses: { "201": { description: "Created" }, "409": { description: "Email exists" } } } },
    "/auth/login": { post: { summary: "Login", responses: { "200": { description: "OK" }, "401": { description: "Invalid credentials" } } } },
    "/auth/refresh": { post: { summary: "Rotate tokens", responses: { "200": { description: "OK" }, "401": { description: "No/invalid refresh" } } } },
    "/auth/logout": { post: { summary: "Logout", responses: { "200": { description: "OK" } } } },
    "/auth/forgot-password": { post: { summary: "Request reset", responses: { "200": { description: "OK" } } } },
    "/auth/reset-password": { post: { summary: "Reset password", responses: { "200": { description: "OK" }, "400": { description: "Invalid token" } } } },
    "/auth/me": { get: { summary: "Current user", responses: { "200": { description: "OK" }, "401": { description: "Unauthenticated" } } } },
    "/users/me": { patch: { summary: "Update profile", responses: { "200": { description: "OK" } } } },
    "/users": { get: { summary: "List users (admin)", responses: { "200": { description: "OK" }, "403": { description: "Forbidden" } } } },
    "/users/{id}/role": { patch: { summary: "Change role (admin)", responses: { "200": { description: "OK" } } } },
    "/vehicles": { get: { summary: "List published vehicles", responses: { "200": { description: "OK" } } } },
    "/vehicles/{slug}": { get: { summary: "Vehicle + parts by slug", responses: { "200": { description: "OK" }, "404": { description: "Not found" } } } },
    "/sessions": { post: { summary: "Start session", responses: { "201": { description: "Created" } } }, get: { summary: "List sessions", responses: { "200": { description: "OK" } } } },
    "/sessions/{id}/end": { post: { summary: "End session", responses: { "200": { description: "OK" } } } },
    "/sessions/{id}/gaze": { post: { summary: "Ingest gaze batch", responses: { "201": { description: "Created" }, "400": { description: "Bad batch" } } } },
    "/sessions/{id}/interactions": { post: { summary: "Ingest interactions", responses: { "201": { description: "Created" } } } },
    "/sessions/{id}/analytics": { get: { summary: "Session analytics", responses: { "200": { description: "OK" }, "403": { description: "Forbidden" } } } },
    "/sessions/{id}/heatmap": { get: { summary: "Session heatmap grid", responses: { "200": { description: "OK" } } } },
    "/sessions/{id}/report": {
      get: {
        summary: "Session report (json/pdf/xlsx)",
        parameters: [{ in: "query", name: "format", schema: { type: "string", enum: ["json", "pdf", "xlsx"] }, description: "Output format (default: json)" }],
        responses: { "200": { description: "OK — JSON body or binary file" }, "403": { description: "Forbidden" }, "404": { description: "Not found" } },
      },
    },
    "/vehicles/{slug}/analytics": { get: { summary: "Vehicle analytics (analyst/admin)", responses: { "200": { description: "OK" }, "404": { description: "Not found" } } } },
    "/vehicles/{slug}/heatmap": { get: { summary: "Vehicle heatmap (analyst/admin)", responses: { "200": { description: "OK" } } } },
    "/vehicles/{slug}/report": {
      get: {
        summary: "Vehicle aggregate report (analyst/admin, json/pdf/xlsx)",
        parameters: [{ in: "query", name: "format", schema: { type: "string", enum: ["json", "pdf", "xlsx"] }, description: "Output format (default: json)" }],
        responses: { "200": { description: "OK — JSON body or binary file" }, "403": { description: "Forbidden" }, "404": { description: "Not found" } },
      },
    },
    "/analytics/overview": { get: { summary: "Global KPIs (analyst/admin)", responses: { "200": { description: "OK" }, "403": { description: "Forbidden" } } } },
    "/sessions/{id}/prediction": { get: { summary: "Session prediction + recommendation", responses: { "200": { description: "OK" }, "403": { description: "Forbidden" } } } },
    "/analytics/recommendations": { get: { summary: "Recommendation aggregates (analyst/admin)", responses: { "200": { description: "OK" }, "403": { description: "Forbidden" } } } },
    "/feedback": { post: { summary: "Submit feedback for a vehicle (authenticated)", responses: { "201": { description: "Created" }, "400": { description: "Invalid input" }, "401": { description: "Unauthenticated" }, "404": { description: "Vehicle not found" } } } },
    "/vehicles/{slug}/feedback": { get: { summary: "Vehicle feedback + summary (analyst/admin)", responses: { "200": { description: "OK" }, "403": { description: "Forbidden" }, "404": { description: "Not found" } } } },
    "/analytics/feedback-summary": { get: { summary: "Global feedback summary (analyst/admin)", responses: { "200": { description: "OK" }, "403": { description: "Forbidden" } } } },
  },
} as const;
